Add an method to reach the unpublish endpoint
sul-dlss/dor-services-client pull request #241
Opened 2022-01-18 16:09 UTC by jcoyne

## Why was this change made?

Ref https://github.com/sul-dlss/argo/issues/2961

## How was this change tested?

## Which documentation and/or configurations were updated?

2022-01-18 19:14 UTC, justinlittman requested changes

2022-01-18 19:14 UTC, justinlittman commented on README.md
> +object_client.publish()
You mean "unpublish"?

2022-01-18 21:21 UTC, jcoyne commented on README.md
> +object_client.publish()
Yes, thanks, fixed.

2022-01-19 12:22 UTC, justinlittman approved these changes

2022-01-19 12:22 UTC, merged