Adds async event creation via rabbit.
sul-dlss/dor-services-client pull request #282
Opened 2022-06-27 12:01 UTC by justinlittman

refs https://github.com/sul-dlss/preservation_catalog/issues/1860

## Why was this change made? 🤔
Non-blocking goodness.

## How was this change tested? 🤨

⚡ ⚠ If this change has cross service impact, ***run [integration tests](https://github.com/sul-dlss/infrastructure-integration-test)*** and/or test in [stage|qa] environment, in addition to specs. ⚡

2022-06-27 19:19 UTC, jcoyne commented
Can we discuss whether this should be in the same library or a new library?  It seems like this new functionality might be completely disjoint from the old synch stuff.

2022-06-27 19:22 UTC, justinlittman commented
Definitely can discuss. My inclination would be to keep in the same library to minimize overhead/changes, until it proves to actually be disjoint and then split.

2022-06-27 19:27 UTC, jcoyne commented
@justinlittman preservation_catalog has no other use for DSC other than the events service. I think that's a pretty good indication of disjunction.

2022-06-27 19:31 UTC, jcoyne requested changes

2022-06-27 19:31 UTC, jcoyne commented on lib/dor/services/client.rb
> +        # @connection ||= ConnectionWrapper.new(connection: build_connection, get_connection: build_connection(with_retries: enable_get_retries))
Cruft?

2022-08-19 17:46 UTC, ndushay commented
this PR needs to be rebased.

2022-08-22 11:03 UTC, closed without merging